CREATE TABLE IF NOT EXISTS public.notes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_token BIGINT      NOT NULL,
    notes            TEXT        NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notes_instrument_token ON public.notes (instrument_token);
