CREATE TABLE IF NOT EXISTS public.breakout_tracker_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_token BIGINT         NOT NULL UNIQUE,
    symbol           TEXT           NOT NULL,
    company_name     TEXT           NOT NULL DEFAULT '',
    breakout_date    DATE           NOT NULL,
    breakout_price   NUMERIC(12, 4) NOT NULL CHECK (breakout_price > 0),
    notes            TEXT           NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_breakout_tracker_entries_symbol
    ON public.breakout_tracker_entries (symbol);
