CREATE TABLE IF NOT EXISTS phase_c_watchlist (
    symbol TEXT PRIMARY KEY,
    instrument_token INTEGER,
    added_on DATE NOT NULL,
    last_seen_on DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'chartinkFilter', -- 'chartinkFilter', 'BREAKOUT_TRIGGERED', 'EXPIRED'
    stock_name TEXT,
    market_cap_bucket TEXT,
    close_price REAL,
    pct_change TEXT,
    volume INTEGER,
    sector TEXT,
    industry TEXT,
    roce_pct REAL,
    ronw_pct REAL,
    net_profit_3q_ago REAL,
    debt_equity_ratio REAL,
    vol_dry_200d_min_count INTEGER,
    vol_dry_60d_min_count INTEGER,
    vol_dry_200d_min_105_count INTEGER,
    vol_dry_60d_min_105_count INTEGER,
    indian_promoter_pct REAL,
    foreign_promoter_pct REAL,
    quarterly_gross_sales REAL,
    high_52w REAL,
    low_52w REAL,
    dist_200d_high_pct REAL,
    dist_200d_low_pct REAL,
    atr_lt_2pct_count INTEGER
);
