BEGIN;

CREATE TABLE IF NOT EXISTS public.groww_volume_shocker_daily (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_date              DATE          NOT NULL,
    source_rank             SMALLINT      NOT NULL,
    exchange                TEXT          NOT NULL,
    symbol                  TEXT          NOT NULL,
    instrument_token        BIGINT        NOT NULL,
    company_name            TEXT          NOT NULL,
    ltp                     NUMERIC(18, 4) NOT NULL,
    close                   NUMERIC(18, 4) NOT NULL,
    market_cap_crore        NUMERIC(20, 2) NOT NULL,
    market_cap_category     TEXT          NOT NULL,
    year_low                NUMERIC(18, 4) NOT NULL,
    year_high               NUMERIC(18, 4) NOT NULL,
    volume                  BIGINT        NOT NULL,
    weekly_average_volume   NUMERIC(20, 4) NOT NULL,
    ingested_at             TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMIT;
