import { useEffect, useMemo, useState } from "react";
import { Alert, Button, Card, Empty, Select, Space, Spin, Table, Tag, Typography } from "antd";
import type { ColumnsType } from "antd/es/table";
import { useAccumulationAnalysis } from "../hooks/useAccumulationAnalysis";
import type { AccumulationCaseSnapshot } from "../types";

const universes = ["nifty_100", "nifty_midcap_150", "nifty_smallcap_250", "nifty_microcap_250"];
export function ForwardAccumulationAnalysisPage() {
  const { runs, summary, timeline, loading, error, loadRuns, loadSummary, loadTimeline, run } = useAccumulationAnalysis();
  const [universeKey, setUniverseKey] = useState("nifty_100"); const [months, setMonths] = useState(6);
  useEffect(() => { void loadRuns().catch(() => undefined); }, [loadRuns]);
  const columns = useMemo<ColumnsType<AccumulationCaseSnapshot>>(() => [
    { title: "Symbol", dataIndex: "symbol", key: "symbol", render: (symbol) => <Button type="link" onClick={() => summary && void loadTimeline(summary.run.id, symbol)}>{symbol}</Button> }, { title: "Base", key: "base", render: (_, row) => `${row.chainStartDate} → ${row.chainEndDate}` }, { title: "Sessions", dataIndex: "chainLengthSessions", key: "length" }, { title: "Hits", dataIndex: "hitCount", key: "hits" }, { title: "Shape", dataIndex: "shape", key: "shape", render: (shape) => <Tag color={shape === "INVALID" ? "red" : shape === "UNCLASSIFIED" ? "gold" : "green"}>{shape}</Tag> }, { title: "Decision", dataIndex: "shapeDecision", key: "decision" }, { title: "Phase D", dataIndex: "firstPhaseDDate", key: "phase" }, { title: "Breakout", dataIndex: "firstBreakoutDate", key: "breakout" }, { title: "Days to D / BO", key: "days", render: (_, row) => `${row.sessionsToPhaseD ?? "-"} / ${row.sessionsToBreakout ?? "-"}` },
  ], [loadTimeline, summary]);
  return <div style={{ padding: 24 }}><Space orientation="vertical" size={16} style={{ width: "100%" }}><div><Typography.Title level={4} style={{ margin: 0 }}>Forward Accumulation Analysis</Typography.Title><Typography.Text type="secondary">Replay saved daily accumulation states without using future evidence.</Typography.Text></div>{error && <Alert type="error" message={error} />}<Card size="small" title="Manual run"><Space><Select value={universeKey} onChange={setUniverseKey} options={universes.map((value) => ({ value, label: value.replaceAll("_", " ") }))} /><Select value={months} onChange={setMonths} options={[1, 3, 6, 9].map((value) => ({ value, label: `${value} months` }))} /><Button type="primary" loading={loading} onClick={() => void run({ universeKey, months }).catch(() => undefined)}>Run replay</Button></Space></Card><Card size="small" title="Saved runs">{runs.map((item) => <Button key={item.id} size="small" style={{ marginRight: 8, marginBottom: 8 }} onClick={() => void loadSummary(item.id)}>{item.universeKey} · {item.months}m · #{item.id}</Button>)}</Card><Card size="small" title={summary ? `Run #${summary.run.id}${summary.isStale ? " · stale" : ""}` : "Run results"}>{loading ? <Spin /> : !summary ? <Empty description="Run a universe to view saved snapshots" /> : <Table rowKey={(row) => `${row.symbol}-${row.chainStartDate}-${row.chainEndDate}`} columns={columns} dataSource={summary.rows} pagination={{ pageSize: 50 }} scroll={{ x: 900 }} />}</Card>{timeline && <Card size="small" title={`Daily timeline · ${timeline.rows.first()?.symbol ?? ""}`}><Table rowKey={(row) => `${row.chainStartDate}-${row.chainEndDate}-${row.asOfDate}`} dataSource={timeline.rows} pagination={{ pageSize: 30 }} columns={[{ title: "As of", dataIndex: "asOfDate" }, { title: "Shape", dataIndex: "shape" }, { title: "Decision", dataIndex: "shapeDecision" }, { title: "Phase D", dataIndex: "firstPhaseDDate" }, { title: "Breakout", dataIndex: "firstBreakoutDate" }]} /></Card>}</Space></div>;
}
