-- =============================================================
-- TradingTool-3 — Master Stock Schema
-- Single stocks table: tags and notes are inline attributes.
-- =============================================================

-- Stocks: master record for every tracked stock.
-- tags JSONB: array of {name, color} objects e.g. [{"name":"Momentum","color":"#ff3d5a"}]
-- notes TEXT: free-form moat/thesis, updated in place (no history).
CREATE TABLE IF NOT EXISTS public.stocks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol           TEXT        NOT NULL,
    instrument_token BIGINT      NOT NULL,
    company_name     TEXT        NOT NULL,
    exchange         TEXT        NOT NULL,
    notes            TEXT,
    priority         INTEGER,
    tags             JSONB       NOT NULL DEFAULT '[]',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(symbol, exchange),
    UNIQUE(instrument_token)
);

CREATE INDEX IF NOT EXISTS idx_stocks_symbol           ON public.stocks(symbol);
CREATE INDEX IF NOT EXISTS idx_stocks_instrument_token ON public.stocks(instrument_token);
CREATE INDEX IF NOT EXISTS idx_stocks_exchange_symbol  ON public.stocks(exchange, symbol);
CREATE INDEX IF NOT EXISTS idx_stocks_tags             ON public.stocks USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_stocks_created_at       ON public.stocks(created_at DESC);

-- Kite tokens: persists Kite Connect access tokens across service restarts.
CREATE TABLE IF NOT EXISTS public.kite_tokens (
    id           SERIAL PRIMARY KEY,
    access_token TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kite_tokens_created ON public.kite_tokens(created_at DESC);

-- Trades: consolidated trade journal. stock_id FK to stocks — null if stock deleted.
CREATE TABLE IF NOT EXISTS public.trades (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id          BIGINT      REFERENCES public.stocks(id) ON DELETE SET NULL,
    nse_symbol        TEXT        NOT NULL,
    quantity          INTEGER     NOT NULL,
    avg_buy_price     NUMERIC(10, 2) NOT NULL,
    today_low         NUMERIC(10, 2),
    stop_loss_percent NUMERIC(5, 2)  NOT NULL,
    stop_loss_price   NUMERIC(10, 2) NOT NULL,
    notes             TEXT,
    trade_date        DATE        NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(stock_id)  -- one consolidated position per stock
);

CREATE INDEX IF NOT EXISTS idx_trades_stock_id   ON public.trades(stock_id);
CREATE INDEX IF NOT EXISTS idx_trades_stock_date ON public.trades(stock_id, trade_date);
CREATE INDEX IF NOT EXISTS idx_trades_created_at ON public.trades(created_at DESC);
