-- =============================================================
-- TradingTool-3 — Master Stock Schema
-- Single stocks table: tags and notes are inline attributes.
-- =============================================================

-- Stocks: master record for every tracked stock.
-- tags JSONB: array of {name, color} objects e.g. [{"name":"Momentum","color":"#ff3d5a"}]
-- notes TEXT: free-form moat/thesis, updated in place (no history).
CREATE TABLE IF NOT EXISTS public.stocks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol           TEXT        NOT NULL,
    instrument_token BIGINT      NOT NULL,
    company_name     TEXT        NOT NULL,
    exchange         TEXT        NOT NULL,
    notes            TEXT,
    priority         INTEGER,
    tags                          JSONB       NOT NULL DEFAULT '[]',
    needs_refresh    BOOLEAN     NOT NULL DEFAULT false,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(symbol, exchange),
    UNIQUE(instrument_token)
);

CREATE INDEX IF NOT EXISTS idx_stocks_symbol           ON public.stocks(symbol);
CREATE INDEX IF NOT EXISTS idx_stocks_instrument_token ON public.stocks(instrument_token);
CREATE INDEX IF NOT EXISTS idx_stocks_exchange_symbol  ON public.stocks(exchange, symbol);
CREATE INDEX IF NOT EXISTS idx_stocks_tags             ON public.stocks USING GIN (tags);
CREATE INDEX IF NOT EXISTS idx_stocks_created_at       ON public.stocks(created_at DESC);

-- Kite tokens: persists Kite Connect access tokens across service restarts.
CREATE TABLE IF NOT EXISTS public.kite_tokens (
    id           SERIAL PRIMARY KEY,
    access_token TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kite_tokens_created ON public.kite_tokens(created_at DESC);

-- Trades: consolidated trade journal. stock_id FK to stocks — null if stock deleted.
CREATE TABLE IF NOT EXISTS public.trades (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id          BIGINT      REFERENCES public.stocks(id) ON DELETE SET NULL,
    nse_symbol        TEXT        NOT NULL,
    quantity          INTEGER     NOT NULL,
    avg_buy_price     NUMERIC(10, 2) NOT NULL,
    today_low         NUMERIC(10, 2),
    stop_loss_percent NUMERIC(5, 2)  NOT NULL,
    stop_loss_price   NUMERIC(10, 2) NOT NULL,
    close_price       NUMERIC(12, 2) NULL,
    close_date        DATE          NULL,
    notes             TEXT,
    trade_date        DATE        NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(stock_id)  -- one consolidated position per stock
);

CREATE INDEX IF NOT EXISTS idx_trades_stock_id   ON public.trades(stock_id);
CREATE INDEX IF NOT EXISTS idx_trades_stock_date ON public.trades(stock_id, trade_date);
CREATE INDEX IF NOT EXISTS idx_trades_created_at ON public.trades(created_at DESC);

-- Stock Indicators Snapshot: JSONB payload of computed daily indicators from Cron Job
CREATE TABLE IF NOT EXISTS public.stock_indicators_snapshot (
    instrument_token BIGINT PRIMARY KEY REFERENCES public.stocks(instrument_token) ON DELETE CASCADE,
    indicators_payload JSONB NOT NULL,
    computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stock_indicators_computed ON public.stock_indicators_snapshot(computed_at DESC);

-- Stock fundamentals: daily snapshot of validated Screener fundamentals
CREATE TABLE IF NOT EXISTS public.stock_fundamentals_daily (
    stock_id BIGINT REFERENCES public.stocks(id),
    instrument_token BIGINT NOT NULL,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    universe TEXT NOT NULL CHECK (universe IN ('largemidcap250', 'smallcap250', 'watchlist')),
    snapshot_date DATE NOT NULL,
    company_name TEXT NOT NULL,
    market_cap_cr NUMERIC(18, 2),
    stock_pe NUMERIC(12, 2),
    roce_percent NUMERIC(8, 2),
    roe_percent NUMERIC(8, 2),
    promoter_holding_percent NUMERIC(8, 2),
    broad_industry TEXT,
    industry TEXT,
    source_name TEXT NOT NULL,
    source_url TEXT NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (instrument_token, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_stock_fundamentals_daily_snapshot_date ON public.stock_fundamentals_daily (snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_fundamentals_daily_symbol_date ON public.stock_fundamentals_daily (symbol, snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_fundamentals_daily_stock_id_date ON public.stock_fundamentals_daily (stock_id, snapshot_date DESC);

-- Remora Strategy: stores one row per stock per day a signal fires.
-- Only inserted when consecutiveDays >= 2, so this is a sparse audit log.
CREATE TABLE IF NOT EXISTS public.remora_signals (
    id               SERIAL PRIMARY KEY,
    stock_id         INTEGER      NOT NULL,
    symbol           TEXT         NOT NULL,
    company_name     TEXT         NOT NULL,
    exchange         TEXT         NOT NULL,
    signal_type      TEXT         NOT NULL CHECK (signal_type IN ('ACCUMULATION', 'DISTRIBUTION')),
    volume_ratio     NUMERIC(6,3) NOT NULL,
    price_change_pct NUMERIC(8,4) NOT NULL,
    consecutive_days INTEGER      NOT NULL,
    signal_date      DATE         NOT NULL,
    delivery_pct     DECIMAL(10, 2),
    delivery_ratio   DECIMAL(10, 2),
    computed_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_remora_signals_stock_date ON public.remora_signals (stock_id, signal_date);
CREATE INDEX IF NOT EXISTS idx_remora_signals_signal_date ON public.remora_signals (signal_date DESC);
CREATE INDEX IF NOT EXISTS idx_remora_signals_signal_type ON public.remora_signals (signal_type);

-- Daily candles: one row per (instrument, date) for long-term metrics
CREATE TABLE IF NOT EXISTS public.daily_candles (
    instrument_token  BIGINT         NOT NULL,
    symbol            TEXT           NOT NULL,
    candle_date       DATE           NOT NULL,
    open              NUMERIC(12, 4) NOT NULL,
    high              NUMERIC(12, 4) NOT NULL,
    low               NUMERIC(12, 4) NOT NULL,
    close             NUMERIC(12, 4) NOT NULL,
    volume            BIGINT         NOT NULL,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    PRIMARY KEY (instrument_token, candle_date)
);

-- Intraday candles: one row per (instrument, interval, timestamp) for intraday patterns
CREATE TABLE IF NOT EXISTS public.intraday_candles (
    instrument_token  BIGINT         NOT NULL,
    symbol            TEXT           NOT NULL,
    interval          TEXT           NOT NULL,
    candle_timestamp  TIMESTAMP      NOT NULL, -- always IST, no timezone (Kite always returns IST)
    open              NUMERIC(12, 4) NOT NULL,
    high              NUMERIC(12, 4) NOT NULL,
    low               NUMERIC(12, 4) NOT NULL,
    close             NUMERIC(12, 4) NOT NULL,
    volume            BIGINT         NOT NULL,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    PRIMARY KEY (instrument_token, interval, candle_timestamp)
);

-- Stock delivery data: daily delivery metrics for each stock
CREATE TABLE IF NOT EXISTS public.stock_delivery_daily (
    stock_id BIGINT REFERENCES public.stocks(id),
    instrument_token BIGINT NOT NULL,
    symbol TEXT NOT NULL,
    exchange TEXT NOT NULL,
    universe TEXT NOT NULL CHECK (universe IN ('largemidcap250', 'smallcap250', 'watchlist')),
    trading_date DATE NOT NULL,
    reconciliation_status TEXT NOT NULL CHECK (reconciliation_status IN ('PRESENT', 'MISSING_FROM_SOURCE')),
    series TEXT,
    ttl_trd_qnty BIGINT,
    deliv_qty BIGINT,
    deliv_per DECIMAL(10, 2),
    source_file_name TEXT,
    source_url TEXT,
    fetched_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (instrument_token, trading_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_candles_symbol      ON public.daily_candles (symbol, candle_date);
CREATE INDEX IF NOT EXISTS idx_intraday_candles_symbol   ON public.intraday_candles (symbol, interval, candle_timestamp);
CREATE INDEX IF NOT EXISTS idx_stock_delivery_daily_trading_date ON public.stock_delivery_daily (trading_date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_delivery_daily_symbol_date ON public.stock_delivery_daily (symbol, trading_date DESC);
CREATE INDEX IF NOT EXISTS idx_stock_delivery_daily_stock_id_date ON public.stock_delivery_daily (stock_id, trading_date DESC);
